### ISSUE TITLE
How to run your method on a different setup?

### ISSUE THREAD

**Issue by fabriziojpiva** [GaoLii/DSP#3]
Hi,

Thanks for your contribution and the publication of your code. I was wondering if it is possible to run your method in a different setup, for example, let's say that I want to adapt Cityscapes ===> BDD. 

I have tried to run this setup by making some minor modifications but it seems like your method is conditioned to these `id2json` class-wise objects, which I do not know how I can generate those files for the aforementioned setup Cityscapes ===> BDD.

Could you please help me out on this?

**Comment by GaoLii** [comment]
The id2json files are used to record which pictures each class appears in, and their corresponding pathes, which are needed when we sample the long-tail classes. The files can be generated with data/preproccess_dataset.py. If you want to train our model with BDD, you must rewrite the code in this file according to its containing classes. Or the easiest way is to not sample the long-tail classes.
